### PR TITLE
Update minor Typo in the readme.

### PR DESCRIPTION
**Pull request by Atavic**

### CODE REVIEW

**Comment by Atavic** [comment]
@kukuriku is working fast!

**Comment by kukuriku** [comment]
we are working now on Tyche, check out: anja, proj and diasm
https://github.com/kukuriku/Anja
asm: https://gist.github.com/kukuriku/1a35bcd6f8d7ddf986e6a646189ac0c8
ranson2
recommended review:
https://github.com/hfiref0x/UACME
hope you enjoy lea..

**Comment by kukuriku** [comment]
we all-saw run a deep web se with links to multiple malware at
https://sp7.co

**Comment by kukuriku** [comment]
enjoy!

**Pull request closed without merging**
